# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: rds-rotate-db-snapshots 1.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "rds-rotate-db-snapshots".freeze
  s.version = "1.0.0".freeze

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Siarhei Kavaliou".freeze]
  s.date = "2024-01-02"
  s.description = "Provides a simple way to rotate RDS DB snapshots with configurable retention periods.".freeze
  s.email = "kovserg@gmail.com".freeze
  s.executables = ["rds-rotate-db-snapshots".freeze]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".github/ISSUE_TEMPLATE/bug_report.md",
    ".github/ISSUE_TEMPLATE/feature_request.md",
    ".github/dependabot.yml",
    ".github/workflows/ci.yml",
    ".github/workflows/codeql.yml",
    ".rspec",
    ".rubocop.yml",
    ".rubocop_todo.yml",
    "CODE_OF_CONDUCT.md",
    "CONTRIBUTING.md",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "SECURITY.md",
    "VERSION",
    "bin/rds-rotate-db-snapshots",
    "lib/rds_rotate_db_snapshots.rb",
    "lib/rds_rotate_db_snapshots/action_wrappers.rb",
    "lib/rds_rotate_db_snapshots/actions.rb",
    "lib/rds_rotate_db_snapshots/options_parser.rb",
    "lib/rds_rotate_db_snapshots/options_parser/options.rb",
    "lib/rds_rotate_db_snapshots/rds_client.rb",
    "rds-rotate-db-snapshots.gemspec",
    "spec/helper.rb",
    "spec/lib/rds_rotate_db_snapshots/action_wrappers_spec.rb",
    "spec/lib/rds_rotate_db_snapshots/actions_spec.rb",
    "spec/lib/rds_rotate_db_snapshots/options_parser_spec.rb",
    "spec/lib/rds_rotate_db_snapshots/rds_client_spec.rb",
    "spec/lib/rds_rotate_db_snapshots_spec.rb"
  ]
  s.homepage = "http://github.com/serg-kovalev/rds-rotate-db-snapshots".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.5.3".freeze
  s.summary = "Amazon RDS DB snapshot rotator".freeze

  s.specification_version = 4

  s.add_runtime_dependency(%q<aws-sdk-rds>.freeze, ["~> 1".freeze])
  s.add_development_dependency(%q<rake>.freeze, [">= 0".freeze])
  s.add_development_dependency(%q<juwelier>.freeze, [">= 0".freeze])
  s.add_development_dependency(%q<pry>.freeze, [">= 0".freeze])
  s.add_development_dependency(%q<pry-byebug>.freeze, [">= 0".freeze])
  s.add_development_dependency(%q<rubocop>.freeze, [">= 0".freeze])
  s.add_development_dependency(%q<rubocop-rspec>.freeze, [">= 0".freeze])
end

