# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

# stub: rds-rotate-db-snapshots 0.5.1 ruby lib

Gem::Specification.new do |s|
  s.name = "rds-rotate-db-snapshots".freeze
  s.version = "0.5.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Siarhei Kavaliou".freeze]
  s.description = "Provides a simple way to rotate RDS DB snapshots with configurable retention periods.".freeze
  s.email = "kovserg@gmail.com".freeze
  s.executables = ["rds-rotate-db-snapshots".freeze]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".github/dependabot.yml",
    ".github/workflows/ci.yml",
    ".github/workflows/codeql.yml",
    ".rspec",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/rds-rotate-db-snapshots",
    "lib/rds_rotate_db_snapshots.rb",
    "lib/rds_rotate_db_snapshots/action_wrappers.rb",
    "lib/rds_rotate_db_snapshots/actions.rb",
    "lib/rds_rotate_db_snapshots/options_parser.rb",
    "lib/rds_rotate_db_snapshots/rds_client.rb",
    "rds-rotate-db-snapshots.gemspec",
    "spec/helper.rb",
    "spec/lib/rds_rotate_db_snapshots/action_wrappers_spec.rb",
    "spec/lib/rds_rotate_db_snapshots/actions_spec.rb",
    "spec/lib/rds_rotate_db_snapshots/options_parser_spec.rb",
    "spec/lib/rds_rotate_db_snapshots/rds_client_spec.rb",
    "spec/lib/rds_rotate_db_snapshots_spec.rb"
  ]
  s.homepage = "http://github.com/serg-kovalev/rds-rotate-db-snapshots".freeze
  s.licenses = ["MIT".freeze]
  s.summary = "Amazon RDS DB snapshot rotator".freeze

  if s.respond_to? :add_runtime_dependency
    s.add_runtime_dependency('aws-sdk-rds'.freeze, ["~> 1"])
    s.add_runtime_dependency('rake'.freeze, [">= 0"])
    s.add_development_dependency('juwelier'.freeze, [">= 0"])
    s.add_development_dependency('pry'.freeze, [">= 0"])
    s.add_development_dependency('pry-byebug'.freeze, [">= 0"])
  else
    s.add_dependency('aws-sdk-rds'.freeze, ["~> 1"])
    s.add_dependency('rake'.freeze, [">= 0"])
    s.add_dependency('juwelier'.freeze, [">= 0"])
    s.add_dependency('pry'.freeze, [">= 0"])
    s.add_dependency('pry-byebug'.freeze, [">= 0"])
  end
  s.metadata['rubygems_mfa_required'] = 'true'
end
