# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: rds-rotate-db-snapshots 0.4.0 ruby lib

Gem::Specification.new do |s|
  s.name = "rds-rotate-db-snapshots".freeze
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Siarhei Kavaliou".freeze]
  s.date = "2022-12-24"
  s.description = "Provides a simple way to rotate RDS DB snapshots with configurable retention periods.".freeze
  s.email = "kovserg@gmail.com".freeze
  s.executables = ["rds-rotate-db-snapshots".freeze]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".travis.yml",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/rds-rotate-db-snapshots",
    "lib/.empty",
    "rds-rotate-db-snapshots.gemspec",
    "test/helper.rb",
    "test/test_rds-rotate-db-snapshots.rb"
  ]
  s.homepage = "http://github.com/serg-kovalev/rds-rotate-db-snapshots".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.3.7".freeze
  s.summary = "Amazon RDS DB snapshot rotator".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4
  end

  if s.respond_to? :add_runtime_dependency then
    s.add_runtime_dependency(%q<aws-sdk-rds>.freeze, ["~> 1"])
    s.add_development_dependency(%q<bundler>.freeze, [">= 0"])
    s.add_development_dependency(%q<simplecov>.freeze, [">= 0"])
    s.add_development_dependency(%q<juwelier>.freeze, [">= 0"])
  else
    s.add_dependency(%q<aws-sdk-rds>.freeze, ["~> 1"])
    s.add_dependency(%q<bundler>.freeze, [">= 0"])
    s.add_dependency(%q<simplecov>.freeze, [">= 0"])
    s.add_dependency(%q<juwelier>.freeze, [">= 0"])
  end
end

