name: "CI"

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ruby_version: [2.7, 3.0, 3.1, 'jruby']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@03b78bdda287ae04217ee12e4b64996630a03542 #v1.131.0
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby_version }}
      - name: Install Bundler
        run: gem install bundler
      - name: Bundle Install
        run: bundle install
      - name: Test
        run: bundle exec rake test
